#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Snapshots the runtime helper source files from @amritk/helpers into a
 * generated TypeScript module that ships with @amritk/generate-parsers.
 *
 * When the CLI runs in 'embedded' mode (helpers not resolvable from outDir),
 * buildSchema() reads these strings and emits them as `_helpers/<name>.ts`
 * files alongside the generated parsers, so the output is self-contained.
 */

const scriptDir = dirname(fileURLToPath(import.meta.url))
const packageDir = resolve(scriptDir, '..')
const helpersSrcDir = resolve(packageDir, '../helpers/src')
const outputPath = resolve(packageDir, 'src/generated/runtime-helper-sources.ts')

const RUNTIME_HELPERS = [
  { src: 'is-object.ts', name: 'is-object.ts' },
  { src: 'validate-array.ts', name: 'validate-array.ts' },
  { src: 'validate-record.ts', name: 'validate-record.ts' },
  { src: 'has-ref.ts', name: 'has-ref.ts' },
] as const

/** Allowed intra-helper relative imports. Anything else means the helper has
 * grown a dependency that won't resolve when embedded into a user's outDir. */
const ALLOWED_RELATIVE_IMPORTS = new Set(['./is-object'])

const validateNoExternalImports = (filename: string, source: string): void => {
  const importLines = source.split('\n').filter((line) => /^\s*import\s/.test(line))
  for (const line of importLines) {
    const match = /from\s+['"]([^'"]+)['"]/.exec(line)
    if (!match) continue
    const spec = match[1]
    if (!spec) continue
    if (spec.startsWith('./') && ALLOWED_RELATIVE_IMPORTS.has(spec)) continue
    throw new Error(
      `Runtime helper ${filename} has a disallowed import: ${spec}\n` +
        `Embedded helpers must be self-contained or only import from other runtime helpers (${[...ALLOWED_RELATIVE_IMPORTS].join(', ')}).`,
    )
  }
}

const main = async (): Promise<void> => {
  const entries: Array<[string, string]> = []
  for (const helper of RUNTIME_HELPERS) {
    const source = await readFile(join(helpersSrcDir, helper.src), 'utf-8')
    validateNoExternalImports(helper.src, source)
    entries.push([helper.name, source])
  }

  const body = entries.map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`).join('\n')

  const output =
    `// AUTO-GENERATED — do not edit by hand.\n` +
    `// Regenerated by packages/generate-parsers/scripts/build-runtime-helpers.ts.\n\n` +
    `export const RUNTIME_HELPER_SOURCES: Readonly<Record<string, string>> = {\n${body}\n}\n`

  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, output, 'utf-8')
  console.log(`Wrote ${outputPath} (${entries.length} helpers)`)
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
