// Official Swagger 2.0 JSON Schema from https://github.com/OAI/OpenAPI-Specification
// External draft-04 $refs (http://json-schema.org/draft-04/schema#/...) are
// inlined as local definitions so @amritk/runtime-validators can resolve them.
export const oas2Schema: object = {
  title: 'A JSON Schema for Swagger 2.0 API.',
  type: 'object',
  required: ['swagger', 'info', 'paths'],
  additionalProperties: false,
  patternProperties: {
    '^x-': { $ref: '#/definitions/vendorExtension' },
  },
  properties: {
    swagger: { type: 'string', enum: ['2.0'] },
    info: { $ref: '#/definitions/info' },
    host: { type: 'string', pattern: '^[^{}/ :\\\\]+(?::\\d+)?$' },
    basePath: { type: 'string', pattern: '^/' },
    schemes: { $ref: '#/definitions/schemesList' },
    consumes: { allOf: [{ $ref: '#/definitions/mediaTypeList' }] },
    produces: { allOf: [{ $ref: '#/definitions/mediaTypeList' }] },
    paths: { $ref: '#/definitions/paths' },
    definitions: { $ref: '#/definitions/definitions' },
    parameters: { $ref: '#/definitions/parameterDefinitions' },
    responses: { $ref: '#/definitions/responseDefinitions' },
    security: { $ref: '#/definitions/security' },
    securityDefinitions: { $ref: '#/definitions/securityDefinitions' },
    tags: { type: 'array', items: { $ref: '#/definitions/tag' }, uniqueItems: true },
    externalDocs: { $ref: '#/definitions/externalDocs' },
  },
  definitions: {
    // --- Helpers inlined from http://json-schema.org/draft-04/schema# ---
    _positiveInteger: { type: 'integer', minimum: 0 },
    _positiveIntegerDefault0: { type: 'integer', minimum: 0, default: 0 },
    _stringArray: { type: 'array', items: { type: 'string' }, minItems: 1, uniqueItems: true },
    _typeEnum: {
      anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' }, minItems: 1, uniqueItems: true }],
    },
    // --- Shared primitive constraint definitions (referenced from header / primitivesItems) ---
    title: { type: 'string' },
    description: { type: 'string' },
    default: {},
    multipleOf: { type: 'number', exclusiveMinimum: 0 },
    maximum: { type: 'number' },
    exclusiveMaximum: { type: 'boolean', default: false },
    minimum: { type: 'number' },
    exclusiveMinimum: { type: 'boolean', default: false },
    maxLength: { $ref: '#/definitions/_positiveInteger' },
    minLength: { $ref: '#/definitions/_positiveIntegerDefault0' },
    pattern: { type: 'string', format: 'regex' },
    maxItems: { $ref: '#/definitions/_positiveInteger' },
    minItems: { $ref: '#/definitions/_positiveIntegerDefault0' },
    uniqueItems: { type: 'boolean', default: false },
    enum: { type: 'array', items: {}, minItems: 1, uniqueItems: true },
    // --- Swagger 2.0 definitions ---
    info: {
      type: 'object',
      required: ['version', 'title'],
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        title: { type: 'string' },
        version: { type: 'string' },
        description: { type: 'string' },
        termsOfService: { type: 'string' },
        contact: { $ref: '#/definitions/contact' },
        license: { $ref: '#/definitions/license' },
      },
    },
    contact: {
      type: 'object',
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        url: { type: 'string', format: 'uri' },
        email: { type: 'string', format: 'email' },
      },
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
    },
    license: {
      type: 'object',
      required: ['name'],
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        url: { type: 'string', format: 'uri' },
      },
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
    },
    paths: {
      type: 'object',
      patternProperties: {
        '^x-': { $ref: '#/definitions/vendorExtension' },
        '^/': { $ref: '#/definitions/pathItem' },
      },
      additionalProperties: false,
    },
    definitions: {
      type: 'object',
      additionalProperties: { $ref: '#/definitions/schema' },
    },
    parameterDefinitions: {
      type: 'object',
      additionalProperties: { $ref: '#/definitions/parameter' },
    },
    responseDefinitions: {
      type: 'object',
      additionalProperties: { $ref: '#/definitions/response' },
    },
    externalDocs: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: {
        description: { type: 'string' },
        url: { type: 'string', format: 'uri' },
      },
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
    },
    examples: {
      type: 'object',
      additionalProperties: true,
    },
    mimeType: { type: 'string' },
    operation: {
      type: 'object',
      required: ['responses'],
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        tags: { type: 'array', items: { type: 'string' }, uniqueItems: true },
        summary: { type: 'string' },
        description: { type: 'string' },
        externalDocs: { $ref: '#/definitions/externalDocs' },
        operationId: { type: 'string' },
        produces: { allOf: [{ $ref: '#/definitions/mediaTypeList' }] },
        consumes: { allOf: [{ $ref: '#/definitions/mediaTypeList' }] },
        parameters: { $ref: '#/definitions/parametersList' },
        responses: { $ref: '#/definitions/responses' },
        schemes: { $ref: '#/definitions/schemesList' },
        deprecated: { type: 'boolean', default: false },
        security: { $ref: '#/definitions/security' },
      },
    },
    pathItem: {
      type: 'object',
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        $ref: { type: 'string' },
        get: { $ref: '#/definitions/operation' },
        put: { $ref: '#/definitions/operation' },
        post: { $ref: '#/definitions/operation' },
        delete: { $ref: '#/definitions/operation' },
        options: { $ref: '#/definitions/operation' },
        head: { $ref: '#/definitions/operation' },
        patch: { $ref: '#/definitions/operation' },
        parameters: { $ref: '#/definitions/parametersList' },
      },
    },
    responses: {
      type: 'object',
      minProperties: 1,
      additionalProperties: false,
      patternProperties: {
        '^([0-9]{3})$|^(default)$': { $ref: '#/definitions/responseValue' },
        '^x-': { $ref: '#/definitions/vendorExtension' },
      },
      not: {
        type: 'object',
        additionalProperties: false,
        patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      },
    },
    responseValue: {
      oneOf: [{ $ref: '#/definitions/response' }, { $ref: '#/definitions/jsonReference' }],
    },
    response: {
      type: 'object',
      required: ['description'],
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        description: { type: 'string' },
        schema: {
          oneOf: [{ $ref: '#/definitions/schema' }, { $ref: '#/definitions/fileSchema' }],
        },
        headers: { $ref: '#/definitions/headers' },
        examples: { $ref: '#/definitions/examples' },
      },
    },
    headers: {
      type: 'object',
      additionalProperties: { $ref: '#/definitions/header' },
    },
    header: {
      type: 'object',
      additionalProperties: false,
      required: ['type'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['string', 'number', 'integer', 'boolean', 'array'] },
        format: { type: 'string' },
        items: { $ref: '#/definitions/primitivesItems' },
        collectionFormat: { $ref: '#/definitions/collectionFormat' },
        default: { $ref: '#/definitions/default' },
        maximum: { $ref: '#/definitions/maximum' },
        exclusiveMaximum: { $ref: '#/definitions/exclusiveMaximum' },
        minimum: { $ref: '#/definitions/minimum' },
        exclusiveMinimum: { $ref: '#/definitions/exclusiveMinimum' },
        maxLength: { $ref: '#/definitions/maxLength' },
        minLength: { $ref: '#/definitions/minLength' },
        pattern: { $ref: '#/definitions/pattern' },
        maxItems: { $ref: '#/definitions/maxItems' },
        minItems: { $ref: '#/definitions/minItems' },
        uniqueItems: { $ref: '#/definitions/uniqueItems' },
        enum: { $ref: '#/definitions/enum' },
        multipleOf: { $ref: '#/definitions/multipleOf' },
        description: { type: 'string' },
      },
    },
    vendorExtension: { additionalProperties: true, additionalItems: true },
    bodyParameter: {
      type: 'object',
      required: ['name', 'in', 'schema'],
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        description: { type: 'string' },
        name: { type: 'string' },
        in: { type: 'string', enum: ['body'] },
        required: { type: 'boolean', default: false },
        schema: { $ref: '#/definitions/schema' },
      },
    },
    headerParameterSubSchema: {
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        required: { type: 'boolean', default: false },
        in: { type: 'string', enum: ['header'] },
        description: { type: 'string' },
        name: { type: 'string' },
        type: { type: 'string', enum: ['string', 'number', 'boolean', 'integer', 'array'] },
        format: { type: 'string' },
        items: { $ref: '#/definitions/primitivesItems' },
        collectionFormat: { $ref: '#/definitions/collectionFormat' },
        default: { $ref: '#/definitions/default' },
        maximum: { $ref: '#/definitions/maximum' },
        exclusiveMaximum: { $ref: '#/definitions/exclusiveMaximum' },
        minimum: { $ref: '#/definitions/minimum' },
        exclusiveMinimum: { $ref: '#/definitions/exclusiveMinimum' },
        maxLength: { $ref: '#/definitions/maxLength' },
        minLength: { $ref: '#/definitions/minLength' },
        pattern: { $ref: '#/definitions/pattern' },
        maxItems: { $ref: '#/definitions/maxItems' },
        minItems: { $ref: '#/definitions/minItems' },
        uniqueItems: { $ref: '#/definitions/uniqueItems' },
        enum: { $ref: '#/definitions/enum' },
        multipleOf: { $ref: '#/definitions/multipleOf' },
      },
    },
    queryParameterSubSchema: {
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        required: { type: 'boolean', default: false },
        in: { type: 'string', enum: ['query'] },
        description: { type: 'string' },
        name: { type: 'string' },
        allowEmptyValue: { type: 'boolean', default: false },
        type: { type: 'string', enum: ['string', 'number', 'boolean', 'integer', 'array'] },
        format: { type: 'string' },
        items: { $ref: '#/definitions/primitivesItems' },
        collectionFormat: { $ref: '#/definitions/collectionFormatWithMulti' },
        default: { $ref: '#/definitions/default' },
        maximum: { $ref: '#/definitions/maximum' },
        exclusiveMaximum: { $ref: '#/definitions/exclusiveMaximum' },
        minimum: { $ref: '#/definitions/minimum' },
        exclusiveMinimum: { $ref: '#/definitions/exclusiveMinimum' },
        maxLength: { $ref: '#/definitions/maxLength' },
        minLength: { $ref: '#/definitions/minLength' },
        pattern: { $ref: '#/definitions/pattern' },
        maxItems: { $ref: '#/definitions/maxItems' },
        minItems: { $ref: '#/definitions/minItems' },
        uniqueItems: { $ref: '#/definitions/uniqueItems' },
        enum: { $ref: '#/definitions/enum' },
        multipleOf: { $ref: '#/definitions/multipleOf' },
      },
    },
    formDataParameterSubSchema: {
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        required: { type: 'boolean', default: false },
        in: { type: 'string', enum: ['formData'] },
        description: { type: 'string' },
        name: { type: 'string' },
        allowEmptyValue: { type: 'boolean', default: false },
        type: {
          type: 'string',
          enum: ['string', 'number', 'boolean', 'integer', 'array', 'file'],
        },
        format: { type: 'string' },
        items: { $ref: '#/definitions/primitivesItems' },
        collectionFormat: { $ref: '#/definitions/collectionFormatWithMulti' },
        default: { $ref: '#/definitions/default' },
        maximum: { $ref: '#/definitions/maximum' },
        exclusiveMaximum: { $ref: '#/definitions/exclusiveMaximum' },
        minimum: { $ref: '#/definitions/minimum' },
        exclusiveMinimum: { $ref: '#/definitions/exclusiveMinimum' },
        maxLength: { $ref: '#/definitions/maxLength' },
        minLength: { $ref: '#/definitions/minLength' },
        pattern: { $ref: '#/definitions/pattern' },
        maxItems: { $ref: '#/definitions/maxItems' },
        minItems: { $ref: '#/definitions/minItems' },
        uniqueItems: { $ref: '#/definitions/uniqueItems' },
        enum: { $ref: '#/definitions/enum' },
        multipleOf: { $ref: '#/definitions/multipleOf' },
      },
    },
    pathParameterSubSchema: {
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      required: ['required'],
      properties: {
        required: { type: 'boolean', enum: [true] },
        in: { type: 'string', enum: ['path'] },
        description: { type: 'string' },
        name: { type: 'string' },
        type: { type: 'string', enum: ['string', 'number', 'boolean', 'integer', 'array'] },
        format: { type: 'string' },
        items: { $ref: '#/definitions/primitivesItems' },
        collectionFormat: { $ref: '#/definitions/collectionFormat' },
        default: { $ref: '#/definitions/default' },
        maximum: { $ref: '#/definitions/maximum' },
        exclusiveMaximum: { $ref: '#/definitions/exclusiveMaximum' },
        minimum: { $ref: '#/definitions/minimum' },
        exclusiveMinimum: { $ref: '#/definitions/exclusiveMinimum' },
        maxLength: { $ref: '#/definitions/maxLength' },
        minLength: { $ref: '#/definitions/minLength' },
        pattern: { $ref: '#/definitions/pattern' },
        maxItems: { $ref: '#/definitions/maxItems' },
        minItems: { $ref: '#/definitions/minItems' },
        uniqueItems: { $ref: '#/definitions/uniqueItems' },
        enum: { $ref: '#/definitions/enum' },
        multipleOf: { $ref: '#/definitions/multipleOf' },
      },
    },
    nonBodyParameter: {
      type: 'object',
      required: ['name', 'in', 'type'],
      oneOf: [
        { $ref: '#/definitions/headerParameterSubSchema' },
        { $ref: '#/definitions/formDataParameterSubSchema' },
        { $ref: '#/definitions/queryParameterSubSchema' },
        { $ref: '#/definitions/pathParameterSubSchema' },
      ],
    },
    parameter: {
      oneOf: [{ $ref: '#/definitions/bodyParameter' }, { $ref: '#/definitions/nonBodyParameter' }],
    },
    schema: {
      type: 'object',
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        $ref: { type: 'string' },
        format: { type: 'string' },
        title: { type: 'string' },
        description: { type: 'string' },
        default: {},
        multipleOf: { type: 'number', exclusiveMinimum: 0 },
        maximum: { type: 'number' },
        exclusiveMaximum: { type: 'boolean', default: false },
        minimum: { type: 'number' },
        exclusiveMinimum: { type: 'boolean', default: false },
        maxLength: { $ref: '#/definitions/_positiveInteger' },
        minLength: { $ref: '#/definitions/_positiveIntegerDefault0' },
        pattern: { type: 'string', format: 'regex' },
        maxItems: { $ref: '#/definitions/_positiveInteger' },
        minItems: { $ref: '#/definitions/_positiveIntegerDefault0' },
        uniqueItems: { type: 'boolean', default: false },
        maxProperties: { $ref: '#/definitions/_positiveInteger' },
        minProperties: { $ref: '#/definitions/_positiveIntegerDefault0' },
        required: { $ref: '#/definitions/_stringArray' },
        enum: { type: 'array', items: {}, minItems: 1, uniqueItems: false },
        additionalProperties: {
          anyOf: [{ $ref: '#/definitions/schema' }, { type: 'boolean' }],
          default: {},
        },
        type: { $ref: '#/definitions/_typeEnum' },
        items: {
          anyOf: [
            { $ref: '#/definitions/schema' },
            { type: 'array', minItems: 1, items: { $ref: '#/definitions/schema' } },
          ],
          default: {},
        },
        allOf: { type: 'array', minItems: 1, items: { $ref: '#/definitions/schema' } },
        properties: {
          type: 'object',
          additionalProperties: { $ref: '#/definitions/schema' },
          default: {},
        },
        discriminator: { type: 'string' },
        readOnly: { type: 'boolean', default: false },
        xml: { $ref: '#/definitions/xml' },
        externalDocs: { $ref: '#/definitions/externalDocs' },
        example: {},
      },
    },
    fileSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['type'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        format: { type: 'string' },
        title: { type: 'string' },
        description: { type: 'string' },
        default: {},
        required: { $ref: '#/definitions/_stringArray' },
        type: { type: 'string', enum: ['file'] },
        readOnly: { type: 'boolean', default: false },
        externalDocs: { $ref: '#/definitions/externalDocs' },
        example: {},
      },
    },
    primitivesItems: {
      type: 'object',
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['string', 'number', 'integer', 'boolean', 'array'] },
        format: { type: 'string' },
        items: { $ref: '#/definitions/primitivesItems' },
        collectionFormat: { $ref: '#/definitions/collectionFormat' },
        default: { $ref: '#/definitions/default' },
        maximum: { $ref: '#/definitions/maximum' },
        exclusiveMaximum: { $ref: '#/definitions/exclusiveMaximum' },
        minimum: { $ref: '#/definitions/minimum' },
        exclusiveMinimum: { $ref: '#/definitions/exclusiveMinimum' },
        maxLength: { $ref: '#/definitions/maxLength' },
        minLength: { $ref: '#/definitions/minLength' },
        pattern: { $ref: '#/definitions/pattern' },
        maxItems: { $ref: '#/definitions/maxItems' },
        minItems: { $ref: '#/definitions/minItems' },
        uniqueItems: { $ref: '#/definitions/uniqueItems' },
        enum: { $ref: '#/definitions/enum' },
        multipleOf: { $ref: '#/definitions/multipleOf' },
      },
    },
    security: {
      type: 'array',
      items: { $ref: '#/definitions/securityRequirement' },
      uniqueItems: true,
    },
    securityRequirement: {
      type: 'object',
      additionalProperties: { type: 'array', items: { type: 'string' }, uniqueItems: true },
    },
    xml: {
      type: 'object',
      additionalProperties: false,
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        name: { type: 'string' },
        namespace: { type: 'string' },
        prefix: { type: 'string' },
        attribute: { type: 'boolean', default: false },
        wrapped: { type: 'boolean', default: false },
      },
    },
    tag: {
      type: 'object',
      additionalProperties: false,
      required: ['name'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        name: { type: 'string' },
        description: { type: 'string' },
        externalDocs: { $ref: '#/definitions/externalDocs' },
      },
    },
    securityDefinitions: {
      type: 'object',
      additionalProperties: {
        oneOf: [
          { $ref: '#/definitions/basicAuthenticationSecurity' },
          { $ref: '#/definitions/apiKeySecurity' },
          { $ref: '#/definitions/oauth2ImplicitSecurity' },
          { $ref: '#/definitions/oauth2PasswordSecurity' },
          { $ref: '#/definitions/oauth2ApplicationSecurity' },
          { $ref: '#/definitions/oauth2AccessCodeSecurity' },
        ],
      },
    },
    basicAuthenticationSecurity: {
      type: 'object',
      additionalProperties: false,
      required: ['type'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['basic'] },
        description: { type: 'string' },
      },
    },
    apiKeySecurity: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'name', 'in'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['apiKey'] },
        name: { type: 'string' },
        in: { type: 'string', enum: ['header', 'query'] },
        description: { type: 'string' },
      },
    },
    oauth2ImplicitSecurity: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'flow', 'authorizationUrl'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['oauth2'] },
        flow: { type: 'string', enum: ['implicit'] },
        scopes: { $ref: '#/definitions/oauth2Scopes' },
        authorizationUrl: { type: 'string', format: 'uri' },
        description: { type: 'string' },
      },
    },
    oauth2PasswordSecurity: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'flow', 'tokenUrl'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['oauth2'] },
        flow: { type: 'string', enum: ['password'] },
        scopes: { $ref: '#/definitions/oauth2Scopes' },
        tokenUrl: { type: 'string', format: 'uri' },
        description: { type: 'string' },
      },
    },
    oauth2ApplicationSecurity: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'flow', 'tokenUrl'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['oauth2'] },
        flow: { type: 'string', enum: ['application'] },
        scopes: { $ref: '#/definitions/oauth2Scopes' },
        tokenUrl: { type: 'string', format: 'uri' },
        description: { type: 'string' },
      },
    },
    oauth2AccessCodeSecurity: {
      type: 'object',
      additionalProperties: false,
      required: ['type', 'flow', 'authorizationUrl', 'tokenUrl'],
      patternProperties: { '^x-': { $ref: '#/definitions/vendorExtension' } },
      properties: {
        type: { type: 'string', enum: ['oauth2'] },
        flow: { type: 'string', enum: ['accessCode'] },
        scopes: { $ref: '#/definitions/oauth2Scopes' },
        authorizationUrl: { type: 'string', format: 'uri' },
        tokenUrl: { type: 'string', format: 'uri' },
        description: { type: 'string' },
      },
    },
    oauth2Scopes: {
      type: 'object',
      additionalProperties: { type: 'string' },
    },
    mediaTypeList: {
      type: 'array',
      items: { $ref: '#/definitions/mimeType' },
      uniqueItems: true,
    },
    parametersList: {
      type: 'array',
      additionalItems: false,
      items: {
        oneOf: [{ $ref: '#/definitions/parameter' }, { $ref: '#/definitions/jsonReference' }],
      },
      uniqueItems: true,
    },
    schemesList: {
      type: 'array',
      items: { type: 'string', enum: ['http', 'https', 'ws', 'wss'] },
      uniqueItems: true,
    },
    collectionFormat: {
      type: 'string',
      enum: ['csv', 'ssv', 'tsv', 'pipes'],
      default: 'csv',
    },
    collectionFormatWithMulti: {
      type: 'string',
      enum: ['csv', 'ssv', 'tsv', 'pipes', 'multi'],
      default: 'csv',
    },
    jsonReference: {
      type: 'object',
      required: ['$ref'],
      additionalProperties: false,
      properties: { $ref: { type: 'string' } },
    },
  },
}
