export type BearerHttpSecuritySchemeObject = {
  /** A short description for security scheme. CommonMark syntax MAY be used for rich text representation. */
  description?: string;
  /** The type of the security scheme. */
  type: "http";
  /** A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes. */
  bearerFormat?: string;
  /** The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235. */
  scheme: "bearer";
};