#!/usr/bin/env node
import { execFile } from 'node:child_process'
import { readdir, unlink, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative, resolve, sep } from 'node:path'
import { promisify } from 'node:util'
import { buildSchema } from '@amritk/generate-parsers'
import { buildValidatorSchema } from '@amritk/generate-validators'
import { deriveRootTypeName } from '@amritk/helpers/derive-root-type-name'
import type { JSONSchema } from 'json-schema-typed/draft-2020-12'

const execFileAsync = promisify(execFile)

import type { CliConfig } from './cli-config'
import { combineGeneratedFiles } from './combine-files'
import { createOutputWriter, type OutputWriter } from './create-output-writer'
import { detectHelpersMode } from './detect-helpers-mode'
import { emitExamples } from './emit-examples'
import { ensureOutputDir } from './ensure-output-dir'
import { HELP_TEXT } from './help-text'
import { loadConfig } from './load-config'
import { loadSchema } from './load-schema'
import { parseCliArgs } from './parse-cli-args'
import { parseMetaRequest } from './parse-meta-request'
import { readVersion } from './read-version'
import { resolveImportExt } from './resolve-import-ext'

/**
 * A valid TypeScript identifier. `rootType` becomes both a `export type <name>`
 * and — lowercased — the output filename, so anything else either emits source
 * that does not compile or, in the case of `../../Escaped`, writes outside the
 * output directory entirely.
 */
const ROOT_TYPE_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/** The schema's base filename without extension, used to derive the root type name. */
const schemaBaseName = (schemaPath: string): string => basename(schemaPath).replace(/\.[^.]+$/, '')

/**
 * Resolves and reports the helpers mode. An explicit `--helpers` wins; otherwise
 * it is auto-detected from the nearest package.json. When detection falls back to
 * embedded, nudge the user toward declaring `@amritk/helpers` so multiple
 * generated trees can share a single runtime helper copy.
 */
const resolveHelpersMode = (config: Partial<CliConfig>, outputDir: string): 'package' | 'embedded' => {
  const helpersMode = config.helpers ?? detectHelpersMode(outputDir)
  console.log(`Helpers mode: ${helpersMode}${config.helpers ? ' (explicit)' : ' (auto-detected)'}`)
  if (!config.helpers && helpersMode === 'embedded') {
    console.log(
      'Tip: add @amritk/helpers as a dependency to share one runtime helper copy across generated trees ' +
        '(or pass --helpers embedded to silence this).',
    )
  }
  return helpersMode
}

/**
 * Extracts the --config flag value from process args before full parsing.
 * We need this early so we can load the config file first, then overlay CLI flags.
 */
const extractConfigPath = (args: readonly string[]): string | undefined => {
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]

    if (arg === '--config' && args[i + 1] && !args[i + 1]?.startsWith('--')) {
      return args[i + 1]
    }

    if (arg?.startsWith('--config=')) {
      return arg.slice('--config='.length)
    }
  }

  return undefined
}

const DEFAULT_BANNER_TEXT =
  'This file was auto-generated by @amritk/mjst.\n * Do not edit it manually — your changes will be overwritten on the next generation.'

const resolveBanner = (banner: boolean | string | undefined): string => {
  if (!banner) return ''
  const text = banner === true ? DEFAULT_BANNER_TEXT : banner
  return `/**\n * ${text}\n */\n\n`
}

/**
 * Stages every file, then commits them in one go, so a failure part-way through
 * leaves the output directory exactly as it was. Returns the committed paths
 * (relative to the writer's root) in the order they were staged.
 */
const commitOrDiscard = async (writer: OutputWriter, stageAll: () => Promise<void>): Promise<string[]> => {
  try {
    await stageAll()
  } catch (error) {
    await writer.discard()
    throw error
  }
  return writer.commit()
}

/** One schema's worth of example output: what to generate, and where it lands. */
type ExampleTask = {
  readonly schema: unknown
  readonly rootTypeName: string
  /** Mirrors the schema's nested location under `--schema-dir`; `''` for a single schema. */
  readonly subDir?: string
}

/**
 * Emits fast-check arbitrary + example files (delegating to {@link emitExamples})
 * and logs each written path. The files land in an `examples/` subdirectory of
 * `outputDir` so they never collide with the parser files, which share the same
 * `<name>.ts` / `index.ts` names. The example sources are left out of `--build`:
 * they import the `fast-check` peer dependency and are meant to be consumed by
 * tests, not compiled alongside the runtime parsers.
 *
 * Every task shares one writer, so the example tree lands as a unit — and it is a
 * *second* writer, created after the parser tree has committed. That ordering
 * matters: a writer reads the manifest once, at creation, so an examples writer
 * made too early would not see the paths the parser run just claimed and would
 * drop them from the manifest it writes. Keeping the examples out of the parser
 * writer is what keeps them out of the `--build` file list, which is exactly the
 * set of paths that run committed.
 */
const runExamples = async (
  config: Partial<CliConfig>,
  outputDir: string,
  tasks: readonly ExampleTask[],
): Promise<void> => {
  const writer = await createOutputWriter(outputDir, config.force)
  const written = await commitOrDiscard(writer, async () => {
    for (const task of tasks) {
      await emitExamples({
        schema: task.schema as JSONSchema,
        rootTypeName: task.rootTypeName,
        writer,
        subDir: task.subDir ?? '',
        bannerPrefix: config.banner ? resolveBanner(config.banner) : '',
        // Spread conditionally: `exactOptionalPropertyTypes` rejects an explicit
        // `undefined` for the optional `typeSuffix`.
        ...(config.typeSuffix !== undefined ? { typeSuffix: config.typeSuffix } : {}),
      })
    }
  })

  for (const path of written) {
    console.log(`Generated example: ${path}`)
  }
}

/**
 * Compiles the generated `.ts` files to `.js`/`.d.ts` with a temporary tsconfig,
 * then removes the intermediate sources. `tsFiles` are paths relative to
 * `outputDir` — and, critically, only the files this run committed, so the
 * cleanup can never delete something that was already in the output directory.
 */
const buildOutput = async (outputDir: string, tsFiles: readonly string[], typesOnly?: boolean): Promise<void> => {
  // Write a minimal tsconfig so tsc can compile the generated files without
  // inheriting settings like allowImportingTsExtensions that block emission.
  // In 'package' mode tsc finds @amritk/helpers via the consumer's node_modules.
  // In 'embedded' mode the helpers live under ./_helpers and need no resolution.
  const tsconfigContent = JSON.stringify(
    {
      compilerOptions: {
        target: 'ESNext',
        module: 'ESNext',
        moduleResolution: 'bundler',
        declaration: true,
        emitDeclarationOnly: typesOnly,
        skipLibCheck: true,
      },
      include: tsFiles.map((file) => `./${file}`),
    },
    null,
    2,
  )

  const tsconfigPath = join(outputDir, '.tsconfig-mjst-build.json')
  await writeFile(tsconfigPath, tsconfigContent, 'utf-8')

  try {
    await execFileAsync('npx', ['tsc', '--project', tsconfigPath])
  } catch (error) {
    const details = error as { code?: string; stdout?: string; stderr?: string }
    // A spawn failure (ENOENT) means the *tool* is missing, not that the code is
    // wrong — pointing the user at "the generated files" would send them hunting
    // for a compile error that doesn't exist. Report the missing executable.
    if (details.code === 'ENOENT') {
      throw new Error(
        'Could not run `npx tsc` to compile the generated files: `npx` (or `tsc`) was not found. ' +
          'Install TypeScript (e.g. `npm install -D typescript`) or drop --build to skip compilation.',
      )
    }
    // Otherwise tsc ran and reported real errors on stdout; surface them so the
    // user sees *what* failed instead of a bare "compilation failed".
    const output = [details.stdout, details.stderr].filter(Boolean).join('\n').trim()
    throw new Error(
      `TypeScript compilation failed. Check the generated files for errors.${output ? `\n\n${output}` : ''}`,
    )
  } finally {
    await unlink(tsconfigPath)
  }

  // Remove the intermediate .ts files now that .js and .d.ts have been produced.
  // Under --types-only tsc emits declarations only, so claiming a `.js` per file
  // (and counting it) advertised output that was never written.
  for (const file of tsFiles) {
    await unlink(join(outputDir, file))
    if (!typesOnly) console.log(`Built: ${file.replace(/\.ts$/, '.js')}`)
    console.log(`Built: ${file.replace(/\.ts$/, '.d.ts')}`)
  }

  console.log(`\nTotal files built: ${tsFiles.length * (typesOnly ? 1 : 2)}`)
}

/** Recursively collects every `*.json` file under `dir`, returning absolute paths. */
const findJsonSchemas = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true })
  const results: string[] = []

  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      // `node_modules` holds dependency schemas that aren't the user's, and
      // dot-directories (`.git`, `.cache`, ...) hold tooling state — descending
      // into either pulls in `.json` files the user never meant to generate from.
      if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue
      results.push(...(await findJsonSchemas(full)))
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      results.push(full)
    }
  }

  return results
}

/**
 * Stages validator files (`validateX` / `isX`) for one schema into `validatorsSubDir`
 * (a path relative to the writer's root). The validators carry the same schema-derived
 * filenames as the parsers, so they live in their own subdirectory to avoid
 * colliding. Returns the staged `.ts` paths so the caller can fold them into a
 * `--build` compilation.
 */
const runValidators = async (
  config: Partial<CliConfig>,
  schema: unknown,
  rootTypeName: string,
  writer: OutputWriter,
  validatorsSubDir: string,
): Promise<string[]> => {
  const files = await buildValidatorSchema(schema as JSONSchema, rootTypeName, config.typeSuffix)
  const staged: string[] = []

  for (const file of files) {
    const content = config.banner ? resolveBanner(config.banner) + file.content : file.content
    const relFilename = join(validatorsSubDir, file.filename)
    await writer.stage(relFilename, content)
    staged.push(relFilename)
  }

  return staged
}

/** Generates parsers for a single schema (the original one-schema-in, one-outDir-out flow). */
const runSingle = async (config: Partial<CliConfig>, schemaPath: string, outputDir: string): Promise<void> => {
  const schema = await loadSchema(config, schemaPath)

  await ensureOutputDir(outputDir)

  const helpersMode = resolveHelpersMode(config, outputDir)

  const rootTypeName = config.rootType ?? deriveRootTypeName(schema, schemaBaseName(schemaPath))
  console.log(`Root type: ${rootTypeName}`)

  const files = await buildSchema(
    schema as JSONSchema,
    rootTypeName,
    undefined,
    config.typesOnly,
    config.logWarnings,
    config.strict,
    helpersMode,
    undefined,
    config.readonly,
    config.stripUnknown,
    config.typeSuffix,
    resolveImportExt(config),
    config.caseInsensitive,
  )

  const writer = await createOutputWriter(outputDir, config.force)
  const written = await commitOrDiscard(writer, async () => {
    for (const file of files) {
      const isHelper = file.filename.startsWith('_helpers/')
      const content = config.banner && !isHelper ? resolveBanner(config.banner) + file.content : file.content
      await writer.stage(file.filename, content)
    }

    if (config.validators) await runValidators(config, schema, rootTypeName, writer, 'validators')
  })

  for (const filename of written) console.log(`Generated: ${filename}`)

  if (config.examples) {
    await runExamples(config, outputDir, [{ schema, rootTypeName }])
  }

  if (config.build) {
    await buildOutput(outputDir, written, config.typesOnly)
  } else {
    console.log(`\nTotal files generated: ${written.length}`)
  }
}

/**
 * Generates a single self-contained file from one schema, concatenating every
 * generated definition (and dropping the cross-file imports that are no longer
 * needed) into `outFilePath`. Currently used for types-only output.
 *
 * The writer is rooted at the file's own directory, which is where its
 * `.mjst-manifest.json` lands. That is a deliberate trade: `--out-file` usually
 * points *into* hand-written source (`--out-file src/types.ts`), so the manifest
 * ends up beside code mjst does not own. We take it anyway, because the
 * alternatives are worse. Ownership has to outlive the process — without a record
 * on disk the second run cannot tell its own output from a file somebody typed,
 * leaving only "always clobber" (the bug this closes) or "always demand
 * `--force`" (which breaks the regenerate-on-schema-change loop that is the whole
 * point of `--out-file`). Anything further away — a cache under `node_modules`,
 * say — disappears on a clean checkout, so CI would refuse to regenerate. And the
 * directory is already one mjst writes into on this path: `--examples` puts an
 * `examples/` tree there and `--build` drops the compiled `.d.ts` beside the
 * source. The manifest lists only the paths this run generated, so it never
 * claims a sibling; it is a hidden file the user can gitignore.
 */
const runSingleFile = async (config: Partial<CliConfig>, schemaPath: string, outFilePath: string): Promise<void> => {
  const schema = await loadSchema(config, schemaPath)
  const outputDir = dirname(outFilePath)
  await ensureOutputDir(outputDir)

  const rootTypeName = config.rootType ?? deriveRootTypeName(schema, schemaBaseName(schemaPath))
  console.log(`Root type: ${rootTypeName}`)

  const files = await buildSchema(
    schema as JSONSchema,
    rootTypeName,
    undefined,
    config.typesOnly,
    config.logWarnings,
    config.strict,
    config.helpers ?? 'package',
    undefined,
    config.readonly,
    config.stripUnknown,
    config.typeSuffix,
    resolveImportExt(config),
    config.caseInsensitive,
  )

  const combined = combineGeneratedFiles(files)

  // Same writer as the directory flows, and for the same reason twice over: the
  // target is often a hand-written `src/types.ts`, which used to be overwritten
  // silently — and then, under `--build`, deleted along with the other
  // intermediate sources, so the user was left with neither their file nor a
  // warning. `--build` is now handed the path this run actually committed.
  const writer = await createOutputWriter(outputDir, config.force)
  const written = await commitOrDiscard(writer, async () => {
    await writer.stage(basename(outFilePath), config.banner ? resolveBanner(config.banner) + combined : combined)
  })

  console.log(`Generated: ${relative(process.cwd(), outFilePath)}`)

  if (config.examples) {
    await runExamples(config, outputDir, [{ schema, rootTypeName }])
  }

  if (config.build) {
    await buildOutput(outputDir, written, config.typesOnly)
  } else {
    console.log(`\nTotal files generated: ${written.length}`)
  }
}

/**
 * Generates parsers for every JSON Schema under `schemaDir`, mirroring the directory
 * layout into `outDir`. Each schema's output lands in its own subdirectory (so files
 * from different schemas never collide) and the runtime helpers are emitted once into a
 * shared `outDir/_helpers/` that every nested parser imports from.
 */
const runRecursive = async (config: Partial<CliConfig>, schemaDir: string, outputDir: string): Promise<void> => {
  if (config.input && config.input !== 'json') {
    console.error("Error: --schemaDir only supports JSON Schema files; remove --input or set it to 'json'.")
    process.exit(1)
  }

  const schemaFiles = await findJsonSchemas(schemaDir)

  if (schemaFiles.length === 0) {
    console.error(`Error: no .json schema files found under ${schemaDir}.`)
    process.exit(1)
  }

  await ensureOutputDir(outputDir)

  const helpersMode = resolveHelpersMode(config, outputDir)

  // Helper sources are identical across schemas, so collect them by filename and
  // write the deduplicated set once at the output root.
  const sharedHelpers = new Map<string, string>()
  const writer = await createOutputWriter(outputDir, config.force)
  /** Example emission is deferred until the parser tree has landed (see below). */
  const exampleTasks: ExampleTask[] = []

  const stageAll = async (): Promise<void> => {
    for (const schemaFile of schemaFiles) {
      const relPath = relative(schemaDir, schemaFile)
      const relNoExt = relPath.slice(0, -'.json'.length)
      // Depth of the schema's output subdirectory, used to build the relative import
      // path back to the shared `_helpers/` at the output root (../, ../../, ...).
      const depth = relNoExt.split(sep).filter(Boolean).length
      const helpersImportPrefix = '../'.repeat(depth)

      const schema = await loadSchema(config, schemaFile)
      const rootTypeName = deriveRootTypeName(schema, schemaBaseName(schemaFile))
      console.log(`\n${relPath} → ${relNoExt}/ (root type: ${rootTypeName})`)

      const files = await buildSchema(
        schema as JSONSchema,
        rootTypeName,
        undefined,
        config.typesOnly,
        config.logWarnings,
        config.strict,
        helpersMode,
        helpersImportPrefix,
        config.readonly,
        config.stripUnknown,
        config.typeSuffix,
        resolveImportExt(config),
        config.caseInsensitive,
      )

      for (const file of files) {
        if (file.filename.startsWith('_helpers/')) {
          sharedHelpers.set(file.filename, file.content)
          continue
        }

        const content = config.banner ? resolveBanner(config.banner) + file.content : file.content
        await writer.stage(join(relNoExt, file.filename), content)
      }

      if (config.validators) {
        // Mirror the parser layout under a top-level `validators/` tree so each
        // schema's validators sit beside their parser counterparts without sharing
        // a filename.
        await runValidators(config, schema, rootTypeName, writer, join('validators', relNoExt))
      }

      if (config.examples) exampleTasks.push({ schema, rootTypeName, subDir: relNoExt })
    }

    for (const [filename, content] of sharedHelpers) {
      await writer.stage(filename, content)
    }
  }

  const writtenTsFiles = await commitOrDiscard(writer, stageAll)

  for (const filename of writtenTsFiles) console.log(`Generated: ${filename}`)

  if (exampleTasks.length > 0) {
    await runExamples(config, outputDir, exampleTasks)
  }

  if (config.build) {
    await buildOutput(outputDir, writtenTsFiles, config.typesOnly)
  } else {
    console.log(`\nTotal files generated: ${writtenTsFiles.length}`)
  }
}

const run = async (): Promise<void> => {
  // Skip the first two args (node executable and script path)
  const args = process.argv.slice(2)

  // `mjst lint <files>` delegates to the linter, which owns its own flag parsing
  // and `--help` (yargs) — so this must run before the shared version/help checks,
  // otherwise `mjst lint --help` would print the codegen help instead.
  if (args[0] === 'lint') {
    const { run: lintRun } = await import('./lint/run')
    const result = await lintRun(args.slice(1))
    if (result.stdout) process.stdout.write(result.stdout)
    if (result.stderr) process.stderr.write(result.stderr)
    process.exit(result.code)
  }

  // `mjst compile-api <routes-module>` compiles @amritk/api route contracts
  // into a fused fetch-handler module. Like lint, it owns its own flags and
  // `--help`, so it must dispatch before the shared version/help checks.
  if (args[0] === 'compile-api') {
    const { run: compileApiRun } = await import('./compile-api/run')
    const result = await compileApiRun(args.slice(1))
    if (result.stdout) process.stdout.write(result.stdout)
    if (result.stderr) process.stderr.write(result.stderr)
    process.exit(result.code)
  }

  const metaRequest = parseMetaRequest(args)

  if (metaRequest === 'version') {
    console.log(await readVersion())
    return
  }

  // Bare `mjst` and `mjst --help` both print usage rather than erroring on a
  // missing --out-dir — a first-run user needs to see the flags, not a failure.
  if (args.length === 0 || metaRequest === 'help') {
    console.log(HELP_TEXT)
    return
  }

  const configPath = extractConfigPath(args)

  // Start with config file values if provided, then overlay CLI flags on top
  const fileConfig = configPath ? await loadConfig(configPath) : {}
  const cliConfig = parseCliArgs(args)
  const config = { ...fileConfig, ...cliConfig }

  if (config.outDir && config.outFile) {
    console.error('Error: provide only one of --out-dir or --out-file, not both.')
    process.exit(1)
  }

  // The root type name becomes a TypeScript identifier *and* the output filename,
  // so an unchecked value is both a compile error (`export type ../../X = …`) and
  // a path traversal — `--root-type '../../Escaped'` wrote outside --out-dir, from
  // a config file as readily as from the command line.
  if (config.rootType !== undefined && !ROOT_TYPE_PATTERN.test(config.rootType)) {
    console.error(
      `Error: invalid --root-type "${config.rootType}". Expected a TypeScript identifier (letters, digits, _ or $, not starting with a digit).`,
    )
    process.exit(1)
  }

  // --root-type names a single root; under --schema-dir each schema derives its
  // own root name, so a single override would be ambiguous.
  if (config.rootType && config.schemaDir) {
    console.error('Error: --root-type cannot be combined with --schema-dir; each schema derives its own root type.')
    process.exit(1)
  }

  // tsc cannot emit from `.ts` import specifiers (allowImportingTsExtensions
  // requires noEmit), so compiled output and stripping-ready sources are
  // mutually exclusive.
  if (config.build && config.importExt === 'ts') {
    console.error('Error: --import-ext ts cannot be combined with --build. Drop --build to keep runnable .ts sources.')
    process.exit(1)
  }

  // Validators are runtime code (validateX / isX), so they have nothing to emit
  // in the type-only flows.
  if (config.validators && config.typesOnly) {
    console.error('Error: --validators cannot be combined with --types-only, which emits no runtime code.')
    process.exit(1)
  }

  if (config.validators && config.outFile) {
    console.error('Error: --validators cannot be combined with --out-file. Use --out-dir to emit validator files.')
    process.exit(1)
  }

  // Single-file output is the alternative to a directory of files.
  if (config.outFile) {
    if (!config.typesOnly) {
      console.error('Error: --out-file currently supports only --types-only output. Add --types-only or use --out-dir.')
      process.exit(1)
    }

    if (config.schemaDir) {
      console.error('Error: --out-file cannot be combined with --schema-dir; use --out-dir for recursive output.')
      process.exit(1)
    }

    if (!config.schema) {
      console.error('Error: --schema is required. Provide a path to a JSON Schema.')
      process.exit(1)
    }

    await runSingleFile(config, resolve(config.schema), resolve(config.outFile))
    return
  }

  if (!config.outDir) {
    console.error('Error: --out-dir or --out-file is required. Provide an output destination for generated files.')
    process.exit(1)
  }

  const outputDir = resolve(config.outDir)

  // schemaDir activates recursive mode and takes precedence over a single schema.
  if (config.schemaDir) {
    await runRecursive(config, resolve(config.schemaDir), outputDir)
    return
  }

  if (!config.schema) {
    console.error('Error: --schema (or --schemaDir) is required. Provide a path to a JSON Schema.')
    process.exit(1)
  }

  await runSingle(config, resolve(config.schema), outputDir)
}

run().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
