#!/usr/bin/env node
import { execFile } from 'node:child_process'
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative, resolve, sep } from 'node:path'
import { promisify } from 'node:util'
import { getAdapter } from '@amritk/adapters/get-adapter'
import { buildSchema } from '@amritk/generate-parsers'
import { deriveRootTypeName } from '@amritk/helpers/derive-root-type-name'
import type { JSONSchema } from 'json-schema-typed/draft-2020-12'

const execFileAsync = promisify(execFile)

import type { CliConfig } from './cli-config'
import { combineGeneratedFiles } from './combine-files'
import { detectHelpersMode } from './detect-helpers-mode'
import { loadConfig } from './load-config'
import { loadSchemaModule } from './load-schema-module'
import { parseCliArgs } from './parse-cli-args'
import { readVersion } from './read-version'

/** True when the args request the CLI version (`version`, `--version`, or `-v`). */
const isVersionRequest = (args: readonly string[]): boolean =>
  args[0] === 'version' || args.includes('--version') || args.includes('-v')

/**
 * Extracts the --config flag value from process args before full parsing.
 * We need this early so we can load the config file first, then overlay CLI flags.
 */
const extractConfigPath = (args: readonly string[]): string | undefined => {
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]

    if (arg === '--config' && args[i + 1] && !args[i + 1]?.startsWith('--')) {
      return args[i + 1]
    }

    if (arg?.startsWith('--config=')) {
      return arg.slice('--config='.length)
    }
  }

  return undefined
}

/** Reads a JSON Schema off disk, or loads a module and converts it via its adapter. */
const loadSchema = async (config: Partial<CliConfig>, schemaPath: string): Promise<unknown> => {
  const inputFormat = config.input ?? 'json'

  if (inputFormat === 'json') {
    return JSON.parse(await readFile(schemaPath, 'utf-8'))
  }

  console.log(`Input format: ${inputFormat}`)
  const source = await loadSchemaModule(schemaPath, config.export)
  return getAdapter(inputFormat).toJSONSchema(source)
}

const DEFAULT_BANNER_TEXT =
  'This file was auto-generated by @amritk/mjst.\n * Do not edit it manually — your changes will be overwritten on the next generation.'

const resolveBanner = (banner: boolean | string | undefined): string => {
  if (!banner) return ''
  const text = banner === true ? DEFAULT_BANNER_TEXT : banner
  return `/**\n * ${text}\n */\n\n`
}

/** Writes a generated file, creating any parent directories the filename implies. */
const writeGeneratedFile = async (baseDir: string, filename: string, content: string): Promise<void> => {
  const filePath = join(baseDir, filename)
  await mkdir(dirname(filePath), { recursive: true })
  await writeFile(filePath, content, 'utf-8')
}

/**
 * Compiles the generated `.ts` files to `.js`/`.d.ts` with a temporary tsconfig,
 * then removes the intermediate sources. `tsFiles` are paths relative to `outputDir`.
 */
const buildOutput = async (outputDir: string, tsFiles: readonly string[], typesOnly?: boolean): Promise<void> => {
  // Write a minimal tsconfig so tsc can compile the generated files without
  // inheriting settings like allowImportingTsExtensions that block emission.
  // In 'package' mode tsc finds @amritk/helpers via the consumer's node_modules.
  // In 'embedded' mode the helpers live under ./_helpers and need no resolution.
  const tsconfigContent = JSON.stringify(
    {
      compilerOptions: {
        target: 'ESNext',
        module: 'ESNext',
        moduleResolution: 'bundler',
        declaration: true,
        emitDeclarationOnly: typesOnly,
        skipLibCheck: true,
      },
      include: tsFiles.map((file) => `./${file}`),
    },
    null,
    2,
  )

  const tsconfigPath = join(outputDir, '.tsconfig-mjst-build.json')
  await writeFile(tsconfigPath, tsconfigContent, 'utf-8')

  try {
    await execFileAsync('npx', ['tsc', '--project', tsconfigPath])
  } catch (error) {
    const details = error as { code?: string; stdout?: string; stderr?: string }
    // A spawn failure (ENOENT) means the *tool* is missing, not that the code is
    // wrong — pointing the user at "the generated files" would send them hunting
    // for a compile error that doesn't exist. Report the missing executable.
    if (details.code === 'ENOENT') {
      throw new Error(
        'Could not run `npx tsc` to compile the generated files: `npx` (or `tsc`) was not found. ' +
          'Install TypeScript (e.g. `npm install -D typescript`) or drop --build to skip compilation.',
      )
    }
    // Otherwise tsc ran and reported real errors on stdout; surface them so the
    // user sees *what* failed instead of a bare "compilation failed".
    const output = [details.stdout, details.stderr].filter(Boolean).join('\n').trim()
    throw new Error(
      `TypeScript compilation failed. Check the generated files for errors.${output ? `\n\n${output}` : ''}`,
    )
  } finally {
    await unlink(tsconfigPath)
  }

  // Remove the intermediate .ts files now that .js and .d.ts have been produced
  for (const file of tsFiles) {
    await unlink(join(outputDir, file))
    console.log(`Built: ${file.replace(/\.ts$/, '.js')}`)
    console.log(`Built: ${file.replace(/\.ts$/, '.d.ts')}`)
  }

  console.log(`\nTotal files built: ${tsFiles.length * 2}`)
}

/** Recursively collects every `*.json` file under `dir`, returning absolute paths. */
const findJsonSchemas = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true })
  const results: string[] = []

  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      // `node_modules` holds dependency schemas that aren't the user's, and
      // dot-directories (`.git`, `.cache`, ...) hold tooling state — descending
      // into either pulls in `.json` files the user never meant to generate from.
      if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue
      results.push(...(await findJsonSchemas(full)))
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      results.push(full)
    }
  }

  return results
}

/** Generates parsers for a single schema (the original one-schema-in, one-outDir-out flow). */
const runSingle = async (config: Partial<CliConfig>, schemaPath: string, outputDir: string): Promise<void> => {
  const schema = await loadSchema(config, schemaPath)

  await mkdir(outputDir, { recursive: true })

  const helpersMode = config.helpers ?? detectHelpersMode(outputDir)
  console.log(`Helpers mode: ${helpersMode}${config.helpers ? ' (explicit)' : ' (auto-detected)'}`)

  const rootTypeName = deriveRootTypeName(schema)
  console.log(`Root type: ${rootTypeName}`)

  const files = await buildSchema(
    schema as JSONSchema,
    rootTypeName,
    undefined,
    config.typesOnly,
    config.logWarnings,
    config.strict,
    helpersMode,
    undefined,
    config.readonly,
    config.stripUnknown,
    config.typeSuffix,
    config.importExt,
  )

  for (const file of files) {
    const isHelper = file.filename.startsWith('_helpers/')
    const content = config.banner && !isHelper ? resolveBanner(config.banner) + file.content : file.content
    await writeGeneratedFile(outputDir, file.filename, content)
    console.log(`Generated: ${file.filename}`)
  }

  if (config.build) {
    await buildOutput(
      outputDir,
      files.map((f) => f.filename),
      config.typesOnly,
    )
  } else {
    console.log(`\nTotal files generated: ${files.length}`)
  }
}

/**
 * Generates a single self-contained file from one schema, concatenating every
 * generated definition (and dropping the cross-file imports that are no longer
 * needed) into `outFilePath`. Currently used for types-only output.
 */
const runSingleFile = async (config: Partial<CliConfig>, schemaPath: string, outFilePath: string): Promise<void> => {
  const schema = await loadSchema(config, schemaPath)
  const outputDir = dirname(outFilePath)
  await mkdir(outputDir, { recursive: true })

  const rootTypeName = deriveRootTypeName(schema)
  console.log(`Root type: ${rootTypeName}`)

  const files = await buildSchema(
    schema as JSONSchema,
    rootTypeName,
    undefined,
    config.typesOnly,
    config.logWarnings,
    config.strict,
    config.helpers ?? 'package',
    undefined,
    config.readonly,
    config.stripUnknown,
    config.typeSuffix,
    config.importExt,
  )

  const combined = combineGeneratedFiles(files)
  await writeFile(outFilePath, config.banner ? resolveBanner(config.banner) + combined : combined, 'utf-8')
  console.log(`Generated: ${relative(process.cwd(), outFilePath)}`)

  if (config.build) {
    await buildOutput(outputDir, [basename(outFilePath)], config.typesOnly)
  } else {
    console.log(`\nTotal files generated: 1`)
  }
}

/**
 * Generates parsers for every JSON Schema under `schemaDir`, mirroring the directory
 * layout into `outDir`. Each schema's output lands in its own subdirectory (so files
 * from different schemas never collide) and the runtime helpers are emitted once into a
 * shared `outDir/_helpers/` that every nested parser imports from.
 */
const runRecursive = async (config: Partial<CliConfig>, schemaDir: string, outputDir: string): Promise<void> => {
  if (config.input && config.input !== 'json') {
    console.error("Error: --schemaDir only supports JSON Schema files; remove --input or set it to 'json'.")
    process.exit(1)
  }

  const schemaFiles = await findJsonSchemas(schemaDir)

  if (schemaFiles.length === 0) {
    console.error(`Error: no .json schema files found under ${schemaDir}.`)
    process.exit(1)
  }

  await mkdir(outputDir, { recursive: true })

  const helpersMode = config.helpers ?? detectHelpersMode(outputDir)
  console.log(`Helpers mode: ${helpersMode}${config.helpers ? ' (explicit)' : ' (auto-detected)'}`)

  // Helper sources are identical across schemas, so collect them by filename and
  // write the deduplicated set once at the output root.
  const sharedHelpers = new Map<string, string>()
  const writtenTsFiles: string[] = []

  for (const schemaFile of schemaFiles) {
    const relPath = relative(schemaDir, schemaFile)
    const relNoExt = relPath.slice(0, -'.json'.length)
    const schemaSubDir = join(outputDir, relNoExt)
    // Depth of the schema's output subdirectory, used to build the relative import
    // path back to the shared `_helpers/` at the output root (../, ../../, ...).
    const depth = relNoExt.split(sep).filter(Boolean).length
    const helpersImportPrefix = '../'.repeat(depth)

    const schema = await loadSchema(config, schemaFile)
    const rootTypeName = deriveRootTypeName(schema)
    console.log(`\n${relPath} → ${relNoExt}/ (root type: ${rootTypeName})`)

    const files = await buildSchema(
      schema as JSONSchema,
      rootTypeName,
      undefined,
      config.typesOnly,
      config.logWarnings,
      config.strict,
      helpersMode,
      helpersImportPrefix,
      config.readonly,
      config.stripUnknown,
      config.typeSuffix,
      config.importExt,
    )

    for (const file of files) {
      if (file.filename.startsWith('_helpers/')) {
        sharedHelpers.set(file.filename, file.content)
        continue
      }

      const content = config.banner ? resolveBanner(config.banner) + file.content : file.content
      await writeGeneratedFile(schemaSubDir, file.filename, content)
      const relativeFilename = join(relNoExt, file.filename)
      writtenTsFiles.push(relativeFilename)
      console.log(`Generated: ${relativeFilename}`)
    }
  }

  for (const [filename, content] of sharedHelpers) {
    await writeGeneratedFile(outputDir, filename, content)
    writtenTsFiles.push(filename)
    console.log(`Generated: ${filename}`)
  }

  if (config.build) {
    await buildOutput(outputDir, writtenTsFiles, config.typesOnly)
  } else {
    console.log(`\nTotal files generated: ${writtenTsFiles.length}`)
  }
}

const run = async (): Promise<void> => {
  // Skip the first two args (node executable and script path)
  const args = process.argv.slice(2)

  if (isVersionRequest(args)) {
    console.log(await readVersion())
    return
  }

  const configPath = extractConfigPath(args)

  // Start with config file values if provided, then overlay CLI flags on top
  const fileConfig = configPath ? await loadConfig(configPath) : {}
  const cliConfig = parseCliArgs(args)
  const config = { ...fileConfig, ...cliConfig }

  if (config.outDir && config.outFile) {
    console.error('Error: provide only one of --out-dir or --out-file, not both.')
    process.exit(1)
  }

  // tsc cannot emit from `.ts` import specifiers (allowImportingTsExtensions
  // requires noEmit), so compiled output and stripping-ready sources are
  // mutually exclusive.
  if (config.build && config.importExt === 'ts') {
    console.error('Error: --import-ext ts cannot be combined with --build. Drop --build to keep runnable .ts sources.')
    process.exit(1)
  }

  // Single-file output is the alternative to a directory of files.
  if (config.outFile) {
    if (!config.typesOnly) {
      console.error('Error: --out-file currently supports only --types-only output. Add --types-only or use --out-dir.')
      process.exit(1)
    }

    if (config.schemaDir) {
      console.error('Error: --out-file cannot be combined with --schema-dir; use --out-dir for recursive output.')
      process.exit(1)
    }

    if (!config.schema) {
      console.error('Error: --schema is required. Provide a path to a JSON Schema.')
      process.exit(1)
    }

    await runSingleFile(config, resolve(config.schema), resolve(config.outFile))
    return
  }

  if (!config.outDir) {
    console.error('Error: --out-dir or --out-file is required. Provide an output destination for generated files.')
    process.exit(1)
  }

  const outputDir = resolve(config.outDir)

  // schemaDir activates recursive mode and takes precedence over a single schema.
  if (config.schemaDir) {
    await runRecursive(config, resolve(config.schemaDir), outputDir)
    return
  }

  if (!config.schema) {
    console.error('Error: --schema (or --schemaDir) is required. Provide a path to a JSON Schema.')
    process.exit(1)
  }

  await runSingle(config, resolve(config.schema), outputDir)
}

run().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
