const DEFAULT_BANNER_TEXT =
  'This file was auto-generated by @amritk/mjst.\n * Do not edit it manually — your changes will be overwritten on the next generation.'

/**
 * Turns the `banner` option into the header prepended to each generated file.
 *
 * A message is wrapped in a JSDoc block, which reads well and is what most
 * headers want. Text that already starts with `//` is emitted as written,
 * because some headers are directives rather than prose, and only the
 * line-comment form counts as one: TypeScript ignores a `@ts-nocheck` inside
 * a block comment, so `--banner "// @ts-nocheck"` was the one header a strict
 * project needed and the one the wrapping made impossible.
 */
export const resolveBanner = (banner: boolean | string | undefined): string => {
  if (!banner) return ''
  const text = banner === true ? DEFAULT_BANNER_TEXT : banner
  if (text.startsWith('//')) return `${text}\n\n`
  return `/**\n * ${text}\n */\n\n`
}
