const DEFAULT_BANNER_TEXT =
  'This file was auto-generated by @amritk/mjst.\n * Do not edit it manually — your changes will be overwritten on the next generation.'

/**
 * True when every non-blank line is already a `//` comment, so the text can be
 * written as is. One line that is not would land in the file as bare source,
 * so a mixed banner stays inside the JSDoc block where any text is safe.
 */
const isLineComments = (text: string): boolean => {
  const lines = text.split('\n').filter((line) => line.trim() !== '')
  return lines.length > 0 && lines.every((line) => line.trimStart().startsWith('//'))
}

/**
 * Turns the `banner` option into the header prepended to each generated file.
 *
 * A message is wrapped in a JSDoc block, which reads well and is what most
 * headers want. Text made only of `//` lines is emitted as written,
 * because some headers are directives rather than prose, and only the
 * line-comment form counts as one: TypeScript ignores a `@ts-nocheck` inside
 * a block comment, so `--banner "// @ts-nocheck"` was the one header a strict
 * project needed and the one the wrapping made impossible.
 */
export const resolveBanner = (banner: boolean | string | undefined): string => {
  if (!banner) return ''
  const text = banner === true ? DEFAULT_BANNER_TEXT : banner
  if (isLineComments(text)) return `${text.trim()}\n\n`
  return `/**\n * ${text}\n */\n\n`
}
