import { describe, expect, it } from 'vitest'

import { resolveBanner } from './resolve-banner'

describe('resolve-banner', () => {
  it('emits nothing when the banner is off', () => {
    expect(resolveBanner(undefined)).toBe('')
    expect(resolveBanner(false)).toBe('')
    expect(resolveBanner('')).toBe('')
  })

  it('wraps the default message in a JSDoc block', () => {
    expect(resolveBanner(true)).toBe(
      '/**\n * This file was auto-generated by @amritk/mjst.\n * Do not edit it manually — your changes will be overwritten on the next generation.\n */\n\n',
    )
  })

  it('wraps a custom message in a JSDoc block', () => {
    expect(resolveBanner('Generated file')).toBe('/**\n * Generated file\n */\n\n')
  })

  // TypeScript only honors `@ts-nocheck` as a line comment, so wrapping this one
  // in a JSDoc block would leave the directive in the file and switch nothing off.
  it('passes line-comment text through as written', () => {
    expect(resolveBanner('// @ts-nocheck')).toBe('// @ts-nocheck\n\n')
    expect(resolveBanner('// @ts-nocheck\n// Generated by mjst')).toBe('// @ts-nocheck\n// Generated by mjst\n\n')
  })

  it('tolerates whitespace around line-comment text', () => {
    expect(resolveBanner('\n  // @ts-nocheck\n')).toBe('// @ts-nocheck\n\n')
  })

  // A line that is not a comment would be bare source at the top of every file,
  // so the whole banner stays inside the JSDoc block instead.
  it('wraps text that mixes comment and plain lines', () => {
    expect(resolveBanner('// @ts-nocheck\nGenerated by mjst')).toBe(
      '/**\n * // @ts-nocheck\nGenerated by mjst\n */\n\n',
    )
  })
})
