import { existsSync } from 'node:fs'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

/**
 * Maintains the repository-root `CHANGELOG.md` — a chronological, aggregated
 * view of every release, newest first.
 *
 * Each package keeps its own `CHANGELOG.md` (written by `changeset version`),
 * but there is no single place to read "what shipped, and when" across the
 * monorepo. This script rolls those per-package notes up into one file.
 *
 * Two modes:
 *
 * - Default (runs in CI right after `changeset version`): find every package
 *   whose newest version is not recorded at the root yet and prepend a single
 *   dated release section aggregating their notes. Idempotent — a second run
 *   with nothing new to record leaves the file untouched — so it is safe for
 *   changesets' release action to re-run whenever the "Version Packages" PR is
 *   regenerated.
 * - Backfill (`--backfill <rounds.json>`): rebuild the whole file from an
 *   explicit, ordered list of historical release rounds. Used once to seed the
 *   history from the merged "Version Packages" PRs; the notes themselves still
 *   come from the per-package changelogs, so the output matches the CI path.
 */

/** A package's notes for one version, ready to render under a release. */
type PackageEntry = {
  name: string
  version: string
  notes: string
}

/**
 * One historical release, as extracted from a merged "Version Packages" PR.
 * `pkgs` holds `@scope/name@version` refs; `date` is the merge date (UTC,
 * `YYYY-MM-DD`) or `null` for a PR that never merged.
 */
type ReleaseRound = {
  date: string | null
  pkgs: string[]
}

/** name -> (version -> notes markdown), one map per published package. */
type PackageRegistry = Map<string, Map<string, string>>

const HEADER = `# Changelog

All notable changes across the packages in this monorepo, newest first. Each
entry below is one release; the notes under it mirror the per-package
\`CHANGELOG.md\` files that changesets maintains. This file is generated by
\`scripts/update-root-changelog.ts\`, which the release workflow runs after
\`changeset version\`.
`

/** The CLI is the product, so it leads every release section. */
const CLI_PACKAGE = '@amritk/mjst'

/**
 * Splits a per-package changelog into a version -> notes map. Insertion order
 * follows the file (newest first), so the first key is always the latest
 * release — which the CI path relies on.
 */
const parseVersions = (changelog: string): Map<string, string> => {
  const versions = new Map<string, string>()
  let current: string | null = null
  let buffer: string[] = []
  const flush = (): void => {
    if (current !== null) versions.set(current, buffer.join('\n').trim())
  }
  for (const line of changelog.split('\n')) {
    const heading = /^## (.+)$/.exec(line)
    if (heading) {
      flush()
      current = heading[1].trim()
      buffer = []
    } else if (current !== null) {
      buffer.push(line)
    }
  }
  flush()
  return versions
}

/** Loads every published package's changelog into a lookup by name and version. */
const loadRegistry = async (root: string): Promise<PackageRegistry> => {
  const registry: PackageRegistry = new Map()
  const packagesDir = join(root, 'packages')
  for (const entry of await readdir(packagesDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const changelogPath = join(packagesDir, entry.name, 'CHANGELOG.md')
    if (!existsSync(changelogPath)) continue
    const pkg = JSON.parse(await readFile(join(packagesDir, entry.name, 'package.json'), 'utf-8')) as { name: string }
    registry.set(pkg.name, parseVersions(await readFile(changelogPath, 'utf-8')))
  }
  return registry
}

/**
 * Splits a `@scope/name@version` ref on its final `@`, so a scoped package name
 * (which also contains an `@`) stays intact.
 */
const splitRef = (ref: string): { name: string; version: string } => {
  const at = ref.lastIndexOf('@')
  return { name: ref.slice(0, at), version: ref.slice(at + 1) }
}

/** CLI first, then alphabetical — a stable order independent of input order. */
const orderEntries = (entries: PackageEntry[]): PackageEntry[] =>
  [...entries].sort((a, b) => {
    if (a.name === CLI_PACKAGE) return b.name === CLI_PACKAGE ? 0 : -1
    if (b.name === CLI_PACKAGE) return 1
    return a.name.localeCompare(b.name)
  })

/**
 * Renders one dated release section. The per-package notes carry `###`
 * subheadings (`### Patch Changes`); those drop a level to `####` so they nest
 * under the package heading here.
 */
const renderRound = (date: string, entries: PackageEntry[]): string => {
  const blocks = orderEntries(entries).map(
    (entry) => `### ${entry.name}@${entry.version}\n\n${entry.notes.replace(/^### /gm, '#### ')}`,
  )
  return `## ${date}\n\n${blocks.join('\n\n')}\n`
}

/**
 * Resolves a round's package refs to renderable entries by looking their notes
 * up in the registry. A ref with no matching notes is dropped and reported, so
 * a gap is loud rather than silent.
 */
const entriesForRound = (round: ReleaseRound, registry: PackageRegistry, warnings: string[]): PackageEntry[] => {
  const entries: PackageEntry[] = []
  for (const ref of round.pkgs) {
    const { name, version } = splitRef(ref)
    const notes = registry.get(name)?.get(version)
    if (notes === undefined) {
      warnings.push(`no notes found for ${ref} (${round.date ?? 'unmerged'})`)
      continue
    }
    entries.push({ name, version, notes })
  }
  return entries
}

/**
 * Inserts a new release section directly beneath the header, above the most
 * recent existing release (or after the header when there are none yet).
 */
const insertSection = (existing: string, section: string): string => {
  const index = existing.search(/^## /m)
  if (index === -1) return `${existing.trimEnd()}\n\n${section}`
  return `${existing.slice(0, index)}${section}\n${existing.slice(index)}`
}

/**
 * Rebuilds the whole changelog from an ordered (oldest-first) list of rounds.
 * Unmerged rounds are skipped; the result is newest-first.
 */
const backfill = (rounds: ReleaseRound[], registry: PackageRegistry, warnings: string[]): string => {
  const sections = rounds
    .filter((round): round is ReleaseRound & { date: string } => round.date !== null)
    .map((round) => renderRound(round.date, entriesForRound(round, registry, warnings)))
    .reverse()
  return `${HEADER}\n${sections.join('\n')}`
}

/**
 * Updates the root `CHANGELOG.md`. Returns whether the file changed and any
 * warnings (missing notes), so a caller — or CI — can surface them.
 */
export const updateRootChangelog = async (
  root: string,
  options: { backfillFrom?: string } = {},
): Promise<{ changed: boolean; warnings: string[] }> => {
  const registry = await loadRegistry(root)
  const warnings: string[] = []
  const rootPath = join(root, 'CHANGELOG.md')

  if (options.backfillFrom !== undefined) {
    const rounds = JSON.parse(await readFile(options.backfillFrom, 'utf-8')) as ReleaseRound[]
    await writeFile(rootPath, backfill(rounds, registry, warnings), 'utf-8')
    return { changed: true, warnings }
  }

  const existing = existsSync(rootPath) ? await readFile(rootPath, 'utf-8') : HEADER
  const unreleased: PackageEntry[] = []
  for (const [name, versions] of registry) {
    const [latest] = versions.keys()
    if (latest === undefined) continue
    if (existing.includes(`### ${name}@${latest}\n`)) continue
    unreleased.push({ name, version: latest, notes: versions.get(latest) as string })
  }
  if (unreleased.length === 0) return { changed: false, warnings }

  const date = new Date().toISOString().slice(0, 10)
  await writeFile(rootPath, insertSection(existing, renderRound(date, unreleased)), 'utf-8')
  return { changed: true, warnings }
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2)
  const backfillFlag = args.indexOf('--backfill')
  const backfillFrom = backfillFlag !== -1 ? args[backfillFlag + 1] : undefined

  updateRootChangelog(join(import.meta.dir, '..'), { backfillFrom })
    .then(({ changed, warnings }) => {
      for (const warning of warnings) console.warn(`warning: ${warning}`)
      console.log(changed ? 'CHANGELOG.md updated' : 'CHANGELOG.md already up to date')
    })
    .catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : error)
      process.exit(1)
    })
}
