import type { IncomingMessage, OutgoingHttpHeaders, ServerResponse } from 'node:http'
import { Readable } from 'node:stream'

import { waitForDrain } from './wait-for-drain'

/**
 * Any Web-standard fetch handler: the `fetch` export of a module generated by
 * `compileToModule`, a Hono/Worker-style `app.fetch`, or a hand-written
 * function. `env` and `executionContext` are the platform arguments Workers
 * pass; on Node there is no per-request platform, so the bridge forwards a
 * fixed `env` (see {@link FetchToNodeHandlerOptions.env}).
 */
export type FetchLikeHandler = (
  request: Request,
  env?: unknown,
  executionContext?: unknown,
) => Promise<Response> | Response

/**
 * Options for {@link fetchToNodeHandler}.
 */
export type FetchToNodeHandlerOptions = {
  /**
   * Passed to the fetch handler as `env` on every request. Node has no
   * per-request platform bindings, so this is a fixed value — typically
   * `process.env` or an app config object, mirroring `toNodeHandler`.
   */
  readonly env?: unknown
}

/**
 * The Node `http.createServer` listener shape the bridge returns — also what
 * Express/Connect expect from a terminal handler.
 */
export type FetchNodeListener = (incoming: IncomingMessage, outgoing: ServerResponse) => void

/**
 * Bridges any fetch handler onto Node's `http` server — the way a module
 * generated by `compileToModule` (which exports only `{ fetch }`) runs under
 * Express or plain `node:http` without giving up the compiled fast path.
 *
 * The incoming message becomes a Web `Request` (absolute URL rebuilt from the
 * `host` header, body streamed — not buffered — for non-GET/HEAD methods),
 * and the handler's `Response` is written back with repeated `set-cookie`
 * values as separate header lines and streaming bodies pumped under the same
 * backpressure rules as `toNodeHandler`.
 *
 * Failure boundary, also mirroring `toNodeHandler`: a handler rejection (or a
 * write failure) before the status line is sent answers a bare 500; once
 * bytes are on the wire, dropping the connection is the only honest option.
 *
 * @example
 * ```typescript
 * import handler from './generated-api'
 * http.createServer(fetchToNodeHandler(handler.fetch)).listen(3000)
 * ```
 */
export const fetchToNodeHandler = (
  handler: FetchLikeHandler,
  options?: FetchToNodeHandlerOptions,
): FetchNodeListener => {
  const env = options?.env
  return (incoming, outgoing) => {
    // The listener itself stays void (Node ignores listener return values);
    // every rejection is handled inside `respond`, so nothing escapes as an
    // unhandled rejection.
    void respond(handler, env, incoming, outgoing)
  }
}

const respond = async (
  handler: FetchLikeHandler,
  env: unknown,
  incoming: IncomingMessage,
  outgoing: ServerResponse,
): Promise<void> => {
  try {
    const response = await handler(toRequest(incoming), env)

    const headers: OutgoingHttpHeaders = {}
    for (const [name, value] of response.headers) {
      // set-cookie is the one header that must not be folded (RFC 6265);
      // getSetCookie is the only un-joined view, and Node's writeHead sends
      // an array value as that many separate header lines.
      if (name !== 'set-cookie') headers[name] = value
    }
    const cookies = response.headers.getSetCookie()
    if (cookies.length > 0) headers['set-cookie'] = cookies
    outgoing.writeHead(response.status, headers)

    const body = response.body
    if (body === null) {
      outgoing.end()
      return
    }
    try {
      for await (const chunk of body as unknown as ReadableStream<Uint8Array>) {
        if (outgoing.write(chunk)) continue
        // The kernel buffer is full — honor backpressure instead of piling
        // chunks into memory. waitForDrain resolves false (never hangs) when
        // the response errors or closes mid-wait; throwing exits the
        // for-await, which cancels the source stream.
        if (!(await waitForDrain(outgoing))) throw new Error('Response closed while awaiting drain')
      }
      outgoing.end()
    } catch {
      // The stream failed mid-flight; the status line is already sent, so
      // the only honest option is to drop the connection.
      outgoing.destroy()
    }
  } catch {
    // A rejected handler or a writeHead failure would otherwise escape as an
    // unhandled rejection. Answer 500 while the status line is unsent; once
    // bytes are on the wire, hang up.
    if (outgoing.headersSent) {
      outgoing.destroy()
      return
    }
    try {
      outgoing.writeHead(500, { 'content-type': 'application/json' })
      outgoing.end('{"error":"internal_error"}')
    } catch {
      outgoing.destroy()
    }
  }
}

/**
 * Rebuilds a Web `Request` from the raw Node message. The URL must be
 * absolute for the `Request` constructor, so the authority comes from the
 * `host` header with a `localhost` fallback for HTTP/1.0 clients that omit
 * it — fetch handlers built on this framework only ever read the path and
 * query anyway.
 */
const toRequest = (incoming: IncomingMessage): Request => {
  const method = (incoming.method ?? 'GET').toUpperCase()
  const url = 'http://' + (incoming.headers.host ?? 'localhost') + (incoming.url ?? '/')
  const headers = new Headers()
  for (const [name, value] of Object.entries(incoming.headers)) {
    if (value === undefined) continue
    if (Array.isArray(value)) {
      for (const item of value) headers.append(name, item)
    } else {
      headers.append(name, value)
    }
  }
  // GET/HEAD requests must not carry a body (the Request constructor
  // rejects one); everything else streams the socket straight through —
  // duplex 'half' is what the fetch spec requires for stream bodies.
  if (method === 'GET' || method === 'HEAD') return new Request(url, { method, headers })
  return new Request(url, { method, headers, body: Readable.toWeb(incoming), duplex: 'half' })
}
