import { execFileSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSchema } from '@amritk/generate-parsers'

import { buildValidatorSchema } from '../src/index.ts'
import { fmtOps } from './measure.ts'
import { assertSchema } from './moltar-data.mjs'

/**
 * mjst under `moltar/typescript-runtime-type-benchmarks`' process model: the
 * four leaderboard cases, generated by this repo's two generators, timed by
 * benny back to back in one process per runtime — see the worker for why one
 * process matters. `moltar.ts` runs this after its per-case tables; it is also
 * its own script for a quick before/after on the generators:
 *
 *   bun run bench:moltar:leaderboard
 */

const BENCH_DIR = fileURLToPath(new URL('.', import.meta.url))
const WORKER = join(BENCH_DIR, 'moltar-leaderboard-worker.mjs')

/** The leaderboard's cases, in the order upstream registers and runs them. */
export const LEADERBOARD_CASES = ['parseSafe', 'parseStrict', 'assertLoose', 'assertStrict'] as const
export type LeaderboardCase = (typeof LEADERBOARD_CASES)[number]

export type LeaderboardResult = { case: LeaderboardCase; ops: number; margin: number; samples: number }

type Runtime = { id: 'bun' | 'node'; command: string; version: string }

/**
 * Generates the four modules the leaderboard case would wire up — parsers for
 * the parse cases, validators for the assert cases — and transpiles them to
 * JavaScript so the same files run under Node and Bun. `parseSafe` is the strict
 * parser with `stripUnknown` over the open schema; `parseStrict` is the strict
 * parser over the closed one. Helpers are embedded so each module dir stands
 * alone.
 */
export const buildLeaderboardModules = async (): Promise<string> => {
  const root = mkdtempSync(join(tmpdir(), 'mjst-moltar-leaderboard-'))
  const transpiler = new Bun.Transpiler({ loader: 'ts' })
  const write = (caseName: LeaderboardCase, files: readonly { filename: string; content: string }[]): void => {
    const dir = join(root, caseName)
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, 'package.json'), '{"type":"module"}')
    for (const file of files) {
      const path = join(dir, file.filename.replace(/\.ts$/, '.js'))
      mkdirSync(dirname(path), { recursive: true })
      writeFileSync(path, transpiler.transformSync(file.content))
    }
  }
  const parser = (typeName: string, strictSchema: boolean, stripUnknown: boolean) =>
    buildSchema(
      assertSchema(strictSchema),
      typeName,
      undefined,
      false,
      false,
      true,
      'embedded',
      './',
      false,
      stripUnknown,
    )
  write('parseSafe', await parser('ParseSafe', false, true))
  write('parseStrict', await parser('ParseStrict', true, false))
  write('assertLoose', await buildValidatorSchema(assertSchema(false), 'AssertLoose'))
  write('assertStrict', await buildValidatorSchema(assertSchema(true), 'AssertStrict'))
  return root
}

/** Runs the four cases in one process under `runtime`. */
export const runLeaderboardWorker = (runtime: Runtime, modulesDir: string): LeaderboardResult[] | null => {
  try {
    const stdout = execFileSync(runtime.command, [WORKER, modulesDir], { encoding: 'utf8', maxBuffer: 1024 * 1024 })
    return JSON.parse(stdout) as LeaderboardResult[]
  } catch (error) {
    const detail = error instanceof Error ? ((error as { stderr?: string }).stderr ?? error.message) : String(error)
    console.error(`  ⚠ ${runtime.id} leaderboard run failed\n${detail.trim()}`)
    return null
  }
}

/** Bun always (this is a Bun script); Node too when it is on PATH. */
export const detectRuntimes = (): Runtime[] => {
  const runtimes: Runtime[] = [{ id: 'bun', command: process.execPath, version: `bun ${Bun.version}` }]
  try {
    const version = execFileSync('node', ['--version'], { encoding: 'utf8' }).trim()
    runtimes.push({ id: 'node', command: 'node', version: `node ${version}` })
  } catch {
    console.error('node not on PATH — measuring Bun only')
  }
  return runtimes
}

const pad = (s: string, width: number): string => s.padEnd(width)
const padStart = (s: string, width: number): string => s.padStart(width)

/** Prints the four-case table, one column per runtime. */
export const runLeaderboard = async (runtimes: Runtime[] = detectRuntimes()): Promise<void> => {
  console.log('## leaderboard process model — mjst, four cases in one process\n')
  console.log('Upstream runs every case a library registers back to back in one process, in this')
  console.log('order, each under benny at its defaults with the result discarded. ± is benny’s margin.\n')
  const modulesDir = await buildLeaderboardModules()
  const columns = runtimes.map((runtime) => ({ runtime, results: runLeaderboardWorker(runtime, modulesDir) }))
  console.log(`  ${pad('case', 14)}${columns.map((c) => padStart(c.runtime.version, 18)).join('')}`)
  for (const caseName of LEADERBOARD_CASES) {
    const cells = columns.map((c) => {
      const result = c.results?.find((r) => r.case === caseName)
      return padStart(result ? `${fmtOps(result.ops)} ±${result.margin.toFixed(0)}%` : 'n/a', 18)
    })
    console.log(`  ${pad(caseName, 14)}${cells.join('')}`)
  }
  console.log()
}

if (import.meta.main) await runLeaderboard()
