import { isObject } from 'mjst-helpers/is-object';

/**
* Security Scheme object
*
* Defines a security scheme that can be used by the operations.  Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter, or as a query parameter), OAuth2's common flows (implicit, password, client credentials, and authorization code) as defined in [RFC6749](https://tools.ietf.org/html/rfc6749), and [[OpenID-Connect-Core]]. Please note that as of 2020, the implicit flow is about to be deprecated by [OAuth 2.0 Security Best Current Practice](https://tools.ietf.org/html/draft-ietf-oauth-security-topics). Recommended for most use cases is Authorization Code Grant flow with PKCE.
* 
* @see {@link https://spec.openapis.org/oas/v3.0.4#security-scheme-object}
*/
export type HttpSecuritySchemeObject = {
  /** **REQUIRED**. The name of the HTTP Authentication scheme to be used in the [Authorization header as defined in RFC7235](https://tools.ietf.org/html/rfc7235#section-5.1). The values used SHOULD be registered in the [IANA Authentication Scheme registry](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml). The value is case-insensitive, as defined in [RFC7235](https://datatracker.ietf.org/doc/html/rfc7235#section-2.1). */
  scheme: string;
  /** A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes. */
  bearerFormat?: string;
  /** A description for security scheme. [CommonMark syntax](https://spec.commonmark.org/) MAY be used for rich text representation. */
  description?: string;
  /** **REQUIRED**. The type of the security scheme. Valid values are `"apiKey"`, `"http"`, `"oauth2"`, `"openIdConnect"`. */
  type: "http";
};

export const parseHttpSecuritySchemeObject = (input: unknown): HttpSecuritySchemeObject => {
  if (!isObject(input)) return {
        scheme: "",
        type: "http",
      };
  return {
    ...input,
    scheme: typeof input?.scheme === "string" ? input?.scheme : (input?.scheme !== undefined ? String(input?.scheme) : ""),
    ...(input.bearerFormat !== undefined && { bearerFormat: typeof input?.bearerFormat === "string" ? input?.bearerFormat : String(input?.bearerFormat) }),
    ...(input.description !== undefined && { description: typeof input?.description === "string" ? input?.description : String(input?.description) }),
    type: typeof input?.type === "string" && ["http"].includes(input?.type as never) ? input?.type : (input?.type !== undefined ? String(input?.type) : "http"),
  } as unknown as HttpSecuritySchemeObject;
}